language: python

env:
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=tests

python:
  - "2.7"
  #- "3.4"
  #- "3.5"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # currently points to 3.6-dev
  
matrix:
  include:
    - python: "3.4"
      env: TEST_SUITE=mypy

# commands to install dependencies
before_install:
  - pip install -r requirements.txt
  - pip install -r $TEST_SUITE""_requirements.txt

# command to run tests
script: ./$TEST_SUITE""_run.sh
