sudo: required
dist: trusty

language: python

env:
  global:
    - TF=0.8.0
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=unit-tests
    - TEST_SUITE=tests

python:
  - "2.7"
  #- "3.4"
  #- "3.5"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # currently points to 3.6-dev
  
matrix:
  include:
    - python: "3.4"
      env: TEST_SUITE=mypy

# commands to install dependencies
before_install:
  - pip install -r requirements.txt
  - if [ ! $TEST_SUITE = 'mypy' ]; then pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-$TF""-cp27-none-linux_x86_64.whl; fi
  - if [ -f $TEST_SUITE""_requirements.txt ]; then pip install -r $TEST_SUITE""_requirements.txt; fi

# command to run tests
script: ./$TEST_SUITE""_run.sh
